version: '3.1'

services:

  crud-api:
    build: .
    environment:
      MONGO_URL: mongo
    ports:
      - 8000:8000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:3.2.20-jessie
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.45.0
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example